/**
 * AGENT_GUIDE.md generator (Phase 11)
 *
 * generateAgentGuide(config, canvases)
 *   Produces a comprehensive AGENT_GUIDE.md and stores it at:
 *   {workspacePath}/.architect/prompts/AGENT_GUIDE.md
 *
 * Called:
 *   - On workspace init
 *   - On each version cut (Ctrl+.)
 */

import { writeFiles } from './io.js';
import { getWorkspacePath } from './flush.js';
import type { WorkspaceConfig, CanvasNode, DesignNode } from '../store/types.js';

// ─── Public API ───────────────────────────────────────────────────────────────

export function generateAgentGuide(
  config: WorkspaceConfig,
  canvases: Record<string, CanvasNode>
): string {
  const lines: string[] = [];

  lines.push(`# AGENT_GUIDE — ${config.name}`);
  lines.push('');
  lines.push(`> Auto-generated by Architect v${config.version}. Do not edit by hand.`);
  lines.push(`> Workspace created: ${config.created_at}`);
  lines.push('');

  // ── 1. Workspace format ────────────────────────────────────────────────────
  lines.push('## 1. Workspace Format');
  lines.push('');
  lines.push('The `.architect/` directory contains:');
  lines.push('');
  lines.push('```');
  lines.push('.architect/');
  lines.push('  config.yaml          — workspace name, root canvas ID, version');
  lines.push('  tree/                — one YAML file per canvas (e.g. canvas.root.yaml)');
  lines.push('  prompts/             — generated guides, including this file');
  lines.push('  versions/            — tar.gz archives cut with Ctrl+. (v1.tar.gz, v2.tar.gz, …)');
  lines.push('  impl/                — implementation task status (impl_status.yaml)');
  lines.push('```');
  lines.push('');
  lines.push('Each `canvas.{id}.yaml` file has the structure:');
  lines.push('');
  lines.push('```yaml');
  lines.push('id: <canvas_id>');
  lines.push('label: <human-readable name>');
  lines.push('narrative: <optional freetext description>');
  lines.push('components:  # blocks (services, modules, data stores, etc.)');
  lines.push('  - id: <node_id>');
  lines.push('    kind: block');
  lines.push('    block_type: service | module | class | function | data-store | external | queue | config');
  lines.push('    name: <display name>');
  lines.push('    status: clean | modified | proposed | ready | running | implemented | failed | dismissed');
  lines.push('    annotation: <optional description>');
  lines.push('    has_children: true/false');
  lines.push('    child_canvas_id: <canvas_id>  # if has_children');
  lines.push('    contract:');
  lines.push('      invariants: [ { id, description, satisfied } ]');
  lines.push('      test_cases:  [ { id, name, status } ]');
  lines.push('    code_links:  [ { file, line_start, line_end, symbol } ]');
  lines.push('connections:  # directed arrows between blocks');
  lines.push('  - id: <arrow_id>');
  lines.push('    kind: arrow');
  lines.push('    arrow_type: calls | reads | writes | publishes | subscribes | depends');
  lines.push('    source: <node_id>');
  lines.push('    target: <node_id>');
  lines.push('    label: <optional>');
  lines.push('    interface:');
  lines.push('      request_schema:  <string>');
  lines.push('      response_schema: <string>');
  lines.push('      description:     <string>');
  lines.push('```');
  lines.push('');

  // ── 2. Reading the design ───────────────────────────────────────────────────
  lines.push('## 2. Reading the Design');
  lines.push('');
  lines.push(`Root canvas ID: \`${config.root_canvas_id}\``);
  lines.push('');
  lines.push('Canvas hierarchy (parent → children):');
  lines.push('');
  _renderCanvasTree(config.root_canvas_id, canvases, lines, 0);
  lines.push('');
  lines.push('**Node status meanings:**');
  lines.push('');
  lines.push('| Status | Meaning |');
  lines.push('|--------|---------|');
  lines.push('| `clean` | No changes since last version cut |');
  lines.push('| `modified` | Changed since last version cut |');
  lines.push('| `proposed` | Agent-proposed, not yet accepted |');
  lines.push('| `ready` | Accepted + spec complete, ready to implement |');
  lines.push('| `running` | Currently being implemented |');
  lines.push('| `implemented` | Code written and verified |');
  lines.push('| `failed` | Implementation attempted and failed |');
  lines.push('| `dismissed` | Explicitly rejected / out of scope |');
  lines.push('');

  // ── 3. Current canvas inventory ────────────────────────────────────────────
  lines.push('## 3. Canvas Inventory');
  lines.push('');
  for (const canvas of Object.values(canvases)) {
    lines.push(`### Canvas: \`${canvas.id}\` — ${canvas.label}`);
    if (canvas.narrative) {
      lines.push('');
      lines.push(`> ${canvas.narrative}`);
    }
    lines.push('');
    if (canvas.components.length === 0) {
      lines.push('_No blocks._');
    } else {
      lines.push('**Blocks:**');
      lines.push('');
      for (const node of canvas.components) {
        lines.push(_renderBlock(node));
      }
    }
    if (canvas.connections.length > 0) {
      lines.push('');
      lines.push('**Connections:**');
      lines.push('');
      for (const arrow of canvas.connections) {
        lines.push(_renderArrow(arrow, canvas.components));
      }
    }
    lines.push('');
  }

  // ── 4. Proposing changes (ACP / changeset format) ──────────────────────────
  lines.push('## 4. Proposing Changes');
  lines.push('');
  lines.push('To propose design changes, emit an **Agent Changeset Proposal (ACP)** as a');
  lines.push('fenced JSON block inside your response:');
  lines.push('');
  lines.push('````json');
  lines.push('{');
  lines.push('  "architect_changeset": {');
  lines.push('    "title": "Short description of change",');
  lines.push('    "target_canvas_id": "<canvas_id>",');
  lines.push('    "nodes": [');
  lines.push('      {');
  lines.push('        "id": "new-node-id",');
  lines.push('        "kind": "block",');
  lines.push('        "block_type": "module",');
  lines.push('        "name": "New Component",');
  lines.push('        "status": "proposed",');
  lines.push('        "annotation": "What this does",');
  lines.push('        "agent_proposed": true');
  lines.push('      }');
  lines.push('    ]');
  lines.push('  }');
  lines.push('}');
  lines.push('````');
  lines.push('');
  lines.push('**Rules for changesets:**');
  lines.push('- Always set `agent_proposed: true` on proposed nodes');
  lines.push('- Use `status: "proposed"` for new additions');
  lines.push('- Only modify the specified `target_canvas_id`');
  lines.push('- Do not change existing node IDs');
  lines.push('- Arrow changesets use `kind: "arrow"` with `source` and `target` referencing existing block IDs');
  lines.push('');

  // ── 5. Contract format ─────────────────────────────────────────────────────
  lines.push('## 5. Contract Format');
  lines.push('');
  lines.push('Each block should have a `contract` describing its correctness guarantees:');
  lines.push('');
  lines.push('```yaml');
  lines.push('contract:');
  lines.push('  invariants:');
  lines.push('    - id: inv-1');
  lines.push('      description: "Postcondition or invariant as prose"');
  lines.push('      satisfied: true  # or false if not yet verified');
  lines.push('  test_cases:');
  lines.push('    - id: tc-1');
  lines.push('      name: test_function_name');
  lines.push('      status: pass | fail | skip | unknown');
  lines.push('```');
  lines.push('');
  lines.push('When proposing a new block, always include an initial `contract` with at least');
  lines.push('one invariant describing the block\'s core guarantee.');
  lines.push('');

  // ── 6. Keyboard shortcuts reference ────────────────────────────────────────
  lines.push('## 6. Quick Reference — Keyboard Shortcuts');
  lines.push('');
  lines.push('| Shortcut | Action |');
  lines.push('|----------|--------|');
  lines.push('| `Ctrl+K` | Open command palette |');
  lines.push('| `1` | Design (conceptual) view |');
  lines.push('| `2` | Toggle implementation drawer |');
  lines.push('| `3` | Code view |');
  lines.push('| `Tab` | Cycle side panel tabs |');
  lines.push('| `N` | New block in current canvas |');
  lines.push('| `E` | Draw arrow from selected block |');
  lines.push('| `Enter` | Open inspector for selected node |');
  lines.push('| `D` | Toggle delta mode |');
  lines.push('| `Ctrl+.` | Cut design version |');
  lines.push('| `Ctrl+B` | New design track |');
  lines.push('| `Ctrl+[/]` | Switch design tracks |');
  lines.push('| `Ctrl+M` | Merge current track |');
  lines.push('| `/` | Focus chat input |');
  lines.push('| `Ctrl+↓` | Drill into selected block\'s child canvas |');
  lines.push('| `Ctrl+↑` | Navigate up |');
  lines.push('| `Space` | Start / pause execution |');
  lines.push('| `A` | Toggle autopilot |');
  lines.push('| `L` | Open log for selected task |');
  lines.push('| `R` | Retry selected failed task |');
  lines.push('');

  return lines.join('\n');
}

/**
 * Write the generated guide to .architect/prompts/AGENT_GUIDE.md
 */
export async function writeAgentGuide(
  config: WorkspaceConfig,
  canvases: Record<string, CanvasNode>
): Promise<void> {
  const workspacePath = getWorkspacePath();
  if (!workspacePath) return;

  const content = generateAgentGuide(config, canvases);
  await writeFiles(workspacePath, [
    ['prompts/AGENT_GUIDE.md', content],
  ]);
  console.info('[agent-guide] Written to .architect/prompts/AGENT_GUIDE.md');
}

// ─── Private helpers ──────────────────────────────────────────────────────────

function _renderCanvasTree(
  canvasId: string,
  canvases: Record<string, CanvasNode>,
  lines: string[],
  depth: number
): void {
  const canvas = canvases[canvasId];
  if (!canvas) return;

  const indent = '  '.repeat(depth);
  lines.push(`${indent}- \`${canvasId}\` — **${canvas.label}**`);

  for (const block of canvas.components) {
    if (block.has_children && block.child_canvas_id && canvases[block.child_canvas_id]) {
      _renderCanvasTree(block.child_canvas_id, canvases, lines, depth + 1);
    }
  }
}

function _renderBlock(node: DesignNode): string {
  const icon = _blockIcon(node.block_type ?? 'module');
  const parts = [`- ${icon} \`${node.id}\` **${node.name}**`];
  if (node.block_type) parts.push(`(${node.block_type})`);
  parts.push(`— *${node.status}*`);
  if (node.annotation) {
    parts.push(`\n  > ${node.annotation}`);
  }
  return parts.join(' ');
}

function _renderArrow(arrow: DesignNode, blocks: DesignNode[]): string {
  const srcName = blocks.find((b) => b.id === arrow.source)?.name ?? arrow.source ?? '?';
  const tgtName = blocks.find((b) => b.id === arrow.target)?.name ?? arrow.target ?? '?';
  const label = arrow.label ? ` \`${arrow.label}\`` : '';
  return `- **${srcName}** →${label} **${tgtName}** (${arrow.arrow_type ?? 'calls'})`;
}

function _blockIcon(blockType: string): string {
  const icons: Record<string, string> = {
    service:    '◆',
    module:     '▣',
    class:      '◇',
    function:   'ƒ',
    'data-store': '⬡',
    external:   '◈',
    queue:      '≡',
    config:     '○',
  };
  return icons[blockType] ?? '□';
}
